In [2]:
##importing different libraries
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt; plt.rcdefaults()
import pandas as pd

In [3]:
import os

cwd = os.getcwd()  ## Get the current working directory (cwd)
files = os.listdir(cwd)  ## Get all the files in that directory
print("Files in %r: %s" % (cwd, files))

Files in '/Users/aarondrexler/Documents': ['Untitled1.ipynb', '~$fraction game.pptx', '.DS_Store', '7stages Rubric.jpg', '7stages Rubric.pdf', 'Aaron Drexler Resume.pdf', '.localized', 'Untitled.ipynb', '~$seating ch.pptx', 'DSC 540', 'adult_income_data.csv.html', 'adult_income_data.csv', 'DSC 540 week 3-4.ipynb', 'notestuesday.pptx', 'Untitled2.ipynb', 'fraction game.pptx', ':0', 'Graphs Q1W7.pptx', 'DSC 550 Week 4.ipynb', 'Boston_housing.csv', 'seating ch.pptx', 'DSC 550 Week 2.ipynb', 'DSC 540.ipynb', 'DSC 550', '.ipynb_checkpoints', 'LAM Syllabus 2021.jpg', '~$Graphs Q1W7.pptx', 'DailyComments.csv', 'adult_income_names.txt']


In [4]:
df = pd.read_csv('DailyComments.csv')
## reads and loads CSV file into dataframe 

In [5]:
import nltk
from nltk.corpus import movie_reviews
import random
## movie reviews has a set of words associated with a positive or negative connotation

In [6]:
nltk.download(["names","stopwords","state_union","twitter_samples","movie_reviews","averaged_perceptron_tagger","vader_lexicon","punkt",])

[nltk_data] Downloading package names to
[nltk_data]     /Users/aarondrexler/nltk_data...
[nltk_data]   Package names is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/aarondrexler/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package state_union to
[nltk_data]     /Users/aarondrexler/nltk_data...
[nltk_data]   Package state_union is already up-to-date!
[nltk_data] Downloading package twitter_samples to
[nltk_data]     /Users/aarondrexler/nltk_data...
[nltk_data]   Package twitter_samples is already up-to-date!
[nltk_data] Downloading package movie_reviews to
[nltk_data]     /Users/aarondrexler/nltk_data...
[nltk_data]   Package movie_reviews is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/aarondrexler/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package vader

True

In [7]:
words = [w for w in nltk.corpus.movie_reviews.words() if w.isalpha()]
## positive and negative words loaded

In [8]:
stopwords = nltk.corpus.stopwords.words("english")
##loading stopwords

In [9]:
words = [w for w in words if w.lower() not in stopwords]
##removes stop words from movie word list

In [10]:
from pprint import pprint

In [11]:
df

Day of Week                                        comments
0      Monday                             Hello, how are you?
1     Tuesday                            Today is a good day!
2   Wednesday  It's my birthday so it's a really special day!
3    Thursday       Today is neither a good day or a bad day!
4      Friday                           I'm having a bad day.
5    Saturday       There' s nothing special happening today.
6      Sunday                      Today is a SUPER good day!

In [12]:
comments= df['comments']
comments

0                               Hello, how are you?
1                              Today is a good day!
2    It's my birthday so it's a really special day!
3         Today is neither a good day or a bad day!
4                             I'm having a bad day.
5         There' s nothing special happening today.
6                        Today is a SUPER good day!
Name: comments, dtype: object

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
vectorizer = CountVectorizer()
x = vectorizer.fit_transform(comments)
print("")
print("vectorized words")
print("")
print(vectorizer.get_feature_names())
print("")
print("Identify Feature Words - Matrix View")
print("")
print(x.toarray())


vectorized words

['are', 'bad', 'birthday', 'day', 'good', 'happening', 'having', 'hello', 'how', 'is', 'it', 'my', 'neither', 'nothing', 'or', 'really', 'so', 'special', 'super', 'there', 'today', 'you']

Identify Feature Words - Matrix View

[[1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 1 0 0 0 0 0 0 2 1 0 0 0 1 1 1 0 0 0 0]
 [0 1 0 2 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0]
 [0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0]
 [0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0]]


In [15]:
df1 = pd.DataFrame({'text' : comments})
df1

text
0                             Hello, how are you?
1                            Today is a good day!
2  It's my birthday so it's a really special day!
3       Today is neither a good day or a bad day!
4                           I'm having a bad day.
5       There' s nothing special happening today.
6                      Today is a SUPER good day!

In [16]:
movie_reviews.categories()

['neg', 'pos']

In [25]:
x=0
for i in df1['text']:
    if i == 'good' or i=='special' or i=='SUPER':
        x=x+1
    elif i == 'bad' or i=='nothing':
        x=x-1
x

0