In [2]:
import numpy as np

In [15]:
arr=np.random.randint(500, size=500)+1

In [23]:
x=arr.reshape(10,50)
x

array([[190, 153, 143, 490,  60,  90, 373, 473, 439,  68, 236, 424, 451,
        266,  72, 102, 370,  16, 388,  72, 500,  14, 210, 221, 166, 365,
        451, 157, 115, 174,   6, 215, 352, 291,  32, 500, 409, 449, 145,
        374, 254,   2, 132, 469, 356, 153, 300, 265,  42,  91],
       [274, 467, 288, 126, 154, 437, 356, 475, 311, 235,  32, 461, 280,
        497, 206,  97, 135, 276, 259, 298, 479, 320, 258,  45, 440, 274,
        166,  13, 488, 250, 186,  13, 423,  28, 461, 421, 295, 453, 146,
         23,  66,  20, 343, 464, 373,  61, 415, 215, 288, 377],
       [136,  72, 246, 210, 292, 264, 230,  17, 111, 197, 284, 353, 386,
        254,   1,  57, 231, 118,  47, 485, 348, 115,  91,  95, 428, 315,
        352,  69, 408, 109,  41, 496, 434, 399,   5, 435, 331, 230, 371,
        184, 378, 329, 246,  20, 185, 127,  73, 313, 204, 492],
       [137, 265, 270, 243, 415, 291, 225, 324, 332, 119, 207,  43, 439,
        297, 308, 419, 149, 184, 101, 217, 336, 473, 248, 264, 486, 262,
     

In [25]:
a=np.sum(x,axis=1)
a

array([12086, 13468, 11614, 12660, 11627, 11673, 12297, 13717, 10903,
       13056])

In [26]:
b=np.sum(x,axis=0)
b

array([2263, 1853, 2252, 2877, 2219, 2783, 2550, 2911, 2433, 2479, 2402,
       2566, 3335, 3149, 1757, 2678, 2209, 2114, 2295, 2390, 3169, 2194,
       2195, 2185, 3414, 2073, 3304, 1589, 3010, 2305, 2272, 1726, 3625,
       2628, 1539, 2712, 2656, 2991, 3078, 2328, 1628, 2315, 2767, 2534,
       2009, 2053, 2679, 2366, 1400, 2842])

In [28]:
c=np.sum(x)
c

123101

In [29]:
np.min(x)

1

In [30]:
np.max(x)

500

In [32]:
np.mean(x)

246.202

In [33]:
np.std(x)

141.6515061550706

In [34]:
x[np.argsort(x[:, 1])]

array([[226,  18, 116, 366, 208, 423,  38, 451, 203, 294, 427,  74,  12,
        347, 147,  29, 316, 358, 155,  73, 277, 336,  98, 189, 473,  53,
        313,  92, 265, 155, 346,  17, 249, 488, 200, 417, 413, 375, 387,
          2,  10, 461, 384, 302,  27,  83,  81, 281, 281, 337],
       [ 53,  28,  70,  56, 100, 107, 413, 210, 126, 339, 218,  80, 476,
        487, 314, 369, 111,   8, 327,   7, 475, 226, 424, 342, 473, 253,
        219,  95, 406, 383, 236,  17, 293, 100,  94, 211, 241,  96, 400,
        222,  48, 331, 472, 307, 137, 363, 106, 401,  13, 344],
       [297,  33, 233, 365, 405, 192, 457, 407,  49, 173, 456, 343, 298,
        198,  62, 447, 127, 445, 155, 157, 251,  55, 199, 381,  13, 191,
        182, 369, 270, 350, 464, 147, 312, 417, 343, 469, 277, 232, 416,
        166,  75, 218,  76, 347, 139, 452, 428, 355,  76,  87],
       [386,  34, 240, 488, 316, 320, 180, 126, 306, 332, 231, 199, 406,
        123,  75, 302, 180, 160, 233, 424, 167,   4, 186, 295, 127,  39,
     

In [54]:
np.sort(x, axis = 1)

array([[  2,   6,  14,  16,  32,  42,  60,  68,  72,  72,  90,  91, 102,
        115, 132, 143, 145, 153, 153, 157, 166, 174, 190, 210, 215, 221,
        236, 254, 265, 266, 291, 300, 352, 356, 365, 370, 373, 374, 388,
        409, 424, 439, 449, 451, 451, 469, 473, 490, 500, 500],
       [ 13,  13,  20,  23,  28,  32,  45,  61,  66,  97, 126, 135, 146,
        154, 166, 186, 206, 215, 235, 250, 258, 259, 274, 274, 276, 280,
        288, 288, 295, 298, 311, 320, 343, 356, 373, 377, 415, 421, 423,
        437, 440, 453, 461, 461, 464, 467, 475, 479, 488, 497],
       [  1,   5,  17,  20,  41,  47,  57,  69,  72,  73,  91,  95, 109,
        111, 115, 118, 127, 136, 184, 185, 197, 204, 210, 230, 230, 231,
        246, 246, 254, 264, 284, 292, 313, 315, 329, 331, 348, 352, 353,
        371, 378, 386, 399, 408, 428, 434, 435, 485, 492, 496],
       [ 24,  39,  43,  56,  89, 101, 108, 117, 119, 137, 140, 149, 168,
        184, 194, 201, 207, 217, 221, 223, 224, 225, 243, 248, 262, 262,
     